### ISSUE TITLE
xgboost Exact performance

### ISSUE THREAD

**Issue by Laurae2** [szilard/GBM-perf#23]
Hardware/Software from: https://github.com/szilard/GBM-perf/issues/12

exact 70 thread:

| Size | Time(s) | AUC |
| ---: | ---: | ---: |
| 0.1M | 1.572 | 0.7330478 |
| 1M | 17.208 | 0.7501779 |
| 10M | 446.807 | 0.7558084 |
| 100M | 5644.698 | (irrelevant) 0.7562036 |

**Comment by szilard** [comment]
| Size | Time (1T) | Time (9T) | Time (18T) | Time (36T) | Time (70T) |
| ---: | ---: | ---: | ---: | ---: | ---: |
| 0.1M | 2.983 | 1..801 | 2.389 | 3.266 | 5.943 |
| 1M | 15.919 | 5.363 | 4.891 | 5.568 | 10.487 |
| 10M | 180.748 | 53.689 | 48.260 | 47.033 | 53.234 |
| 100M | 1930.816 | 578.734 | 560.296 | 507.580 |  |
