### ISSUE TITLE
Problem with GPU version of XGBoost

### ISSUE THREAD

**Issue by miguelgfierro** [szilard/GBM-perf#3]
Hi @szilard  I'm trying to create a similar benchmark. I'm having problems when compiling the last version of xgboost. I used yesterday's commit:

```bash
commit 65d2513714b4d3c4f5e8d0ebad607b1f81b46379
Author: wxchan <wxchan@users.noreply.github.com>
Date:   Mon Jun 12 21:33:42 2017 +0800
    [python-package] fix sklearn n_jobs/nthreads and seed/random_state bug  (#2378)
    * add a testcase causing RuntimeError
    * move seed/random_state/nthread/n_jobs check to get_xgb_params()
    * fix failed test
```

Could you share the commit you used?

**Comment by szilard** [comment]
Sure, it's in the main `README.md`:

Initially I used the latest CRAN R package version.

For GPUs I used github commit 6776292... (from python)

**Comment by miguelgfierro** [comment]
This right?
6776292951565c8cd72e69afd9d94de1474f00c0

**Comment by szilard** [comment]
I guess, I saved only first 7 digits
