### ISSUE TITLE
issue to run the 'build' command

### ISSUE THREAD

**Issue by pint1022** [szilard/GBM-perf#32]
Hi
I tried to run 'sudo docker build --build-arg CACHE_DATE=$(date + '1') -t gbmperf_cpu .' There is an error at the step 8/15 to install 'h2o'. The error is "
Content type 'application/x-tar' length 123701774 bytes (118.0 MB)
==================================================
downloaded 118.0 MB

ERROR: dependency ‘RCurl’ is not available for package ‘h2o’
* removing ‘/usr/local/lib/R/site-library/h2o’

The downloaded source packages are in
	‘/tmp/downloaded_packages’
Warning message:
In install.packages(pkgs, ...) :
  installation of package ‘h2o’ had non-zero exit status
"
After that, the process seems continuing, but there is no test result to follow the step 15/15.

I am not sure what to do next after 15/15 to get the results. Or since there is an error, the test cant' run.

**Comment by szilard** [comment]
Looks like some dependencies have changed in the latest versions.

Try adding `RCurl` to Line 11 `RUN install2.r ROCR data.table` in the Dockerfile:
```
RUN install2.r ROCR data.table RCurl
```

**Comment by pint1022** [comment]
fixed. thanks

**Comment by pint1022** [comment]
issue is fixed.
