### ISSUE TITLE
KDD conference - let's meet

### ISSUE THREAD

**Issue by szilard** [szilard/GBM-perf#6]
Any of you guys @guolinke @Laurae2 @RAMitchell @tqchen coming to KDD conference next week in Halifax, Canada? Let's meet there if you are coming...

**Comment by tqchen** [comment]
Unfortunately I am not there, but have fun!

**Comment by Laurae2** [comment]
Won't be there, but hoping you will have lot of fun! (and maybe interesting feedback from your 
![image](https://user-images.githubusercontent.com/9083669/29252860-2b23fac4-806f-11e7-9e3d-e946d0251782.png)
)

**Comment by guolinke** [comment]
sorry, I won't be there. Hoping you will have fun and looking forward to your talk.
