### ISSUE TITLE
xgboost CPU slowdown (on some servers/high number of cores)

### ISSUE THREAD

**Issue by szilard** [szilard/GBM-perf#9]
Weird slowdown in xgboost in latest versions with large number of threads on single-socket high-core-count CPUs (this is separate from the slowdown on multi-socket/multi-NUMA-node CPUs).

Investigated with @Laurae2 (to be reported to xgboost devs).

The issue popped up when rerunning this benchmark with new versions of xgboost (on 32 core, 1-socket/1-NUMA node r4.8xlarge):

VER=v0.72
```
threads   runtime(s)       AUC
1           37.871        0.7494959
16          14.262        0.7494959
32          16.304        0.7494959
```

VER=v0.82
```
threads   runtime(s)   AUC
1         29.532      0.7494959
16        15.805      0.7494959
32       176.856      0.7494959
```

Code here: https://github.com/szilard/GBM-perf/tree/master/wip-testing/xgboost-slowdown

**Comment by Laurae2** [comment]
More data to come later

Commit dmlc/xgboost@37dc82c, 1 socket 1-36, 2 sockets 37-72

```
01: 21.447s
02: 23.967s
03: 16.860s
04: 16.341s
05: 15.253s
06: 15.387s
07: 15.918s
08: 14.092s
09: 14.011s
10: 14.599s
11: 16.304s
12: 15.072s
13: 16.103s
14: 16.031s
15: 16.269s
16: 15.843s
17: 16.736s
18: 16.716s
19: 16.719s
20: 16.512s
21: 16.739s
22: 16.908s
23: 17.802s
24: 17.840s
25: 17.494s
26: 17.325s
27: 17.717s
28: 21.898s
29: 23.704s
30: 34.937s
31: 38.176s
32: 42.264s
33: 48.550s
34: 59.325s
35: 63.258s
36: 72.464s
37: 77.663s
38: 85.466s
39: 93.152s
40: 103.581s
41: 116.534s
42: 132.385s
43: 145.701s
44: 159.930s
45: 171.141s
46: 184.014s
47: 194.288s
48: 207.258s
49: 218.728s
50: 229.320s
51: 247.662s
52: 258.362s
53: 269.907s
54: 274.621s
55: 283.143s
56: 296.118s
57: 302.987s
58: 310.314s
59: 322.396s
60: 333.417s
61: 338.434s
62: 346.571s
63: 359.035s
64: 369.134s
65: 379.222s
66: 385.047s
67: 396.004s
68: 401.435s
69: 403.000s
70: 397.683s
71: 403.750s
72: 435.044s
```

**Comment by szilard** [comment]
VER=v0.7  (Dec 30, 2017)

```
1 30.946 0.7494959
2 20.094 0.7494959
4 19.955 0.7494959
8 16.961 0.7494959
16 16.049 0.7494959
32 17.014 0.7494959
```

**Comment by szilard** [comment]
VER=dade7c3 (from @Laurae2 )

```
1 32.16 0.7494959
2 20.538 0.7494959
4 21.005 0.7494959
8 17.161 0.7494959
16 16.432 0.7494959
32 16.849 0.7494959
```

VER=5f151c5

```
 1 31.504 0.7494959
2 25.475 0.7494959
4 18.222 0.7494959
8 16.094 0.7494959
16 15.943 0.7494959
32 579.058 0.7494959
```

**Comment by szilard** [comment]
m4.4xlarge

CPU(s):                16
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
CPU MHz:               2300.092
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-15

**Comment by szilard** [comment]
m5.12xlarge

CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2500.000
BogoMIPS:              5000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0-47

VER=v0.81
```
```

VER=v0.82
```
```

**Comment by szilard** [comment]
Looks fixed 👍
